<?php
echo '<!DOCTYPE html>';
echo '<html lang="ru">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Отчет по практической работе №6</title>';
echo '<style>';
echo 'h1 {';
echo 'text-align: center;';
echo 'margin-bottom: 50px;';
echo '}';
echo '';
echo 'table {';
echo 'width: 100%;';
echo 'border-collapse: collapse;';
echo '}';
echo '';
echo 'th, td {';
echo 'padding: 10px;';
echo 'border: 1px solid black;';
echo 'text-align: center;';
echo '}';
echo '';
echo 'th {';
echo 'background-color: #ddd;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<h1>Титульный лист</h1>';
echo '<p>Название практической работы: Практическая работа №6</p>';
echo '<p>ФИО студента: зиннатуллин б.м.</p>';
echo '<p>Дата:',date ("d.m.Y");'</p>';
echo '<h1>Отчет по практической работе №6</h1>';
echo '<table>';
echo '<thead>';
echo '<tr>';
echo '<th>Критерий оценки</th>';
echo '<th>Оценка</th>';
echo '<th>Комментарий</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<td>Выполнение задания</td>';
echo '<td>5</td>';
echo '<td>Все задания выполнены в срок и соответствуют требованиям.</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Квалитет кода</td>';
echo '<td>4</td>';
echo '<td>Код читаемый и хорошо структурирован, но можно улучшить комментарии.</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Соответствие стандартам</td>';
echo '<td>5</td>';
echo '<td>Соответствие стандартам PSR-1 и PSR-12 на высоком уровне.</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Оригинальность</td>';
echo '<td>3</td>';
echo '<td>Решение задач стандартное, можно добавить больше оригинальности.</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Общая оценка</td>';
echo '<td>4.5</td>';
echo '<td>Отличная работа, можно улучшить комментарии в коде.</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</body>';
echo '</html>';
?>
